### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [TheShadow29/vognet-pytorch#3]
How long does the model need to train? Could I use one 1080Ti GPU to reproduce the results?

**Comment by TheShadow29** [comment]
@AmingWu thank you for your interest.

It depends on the particular setting you are using. For GT5 setting, it takes around 30mins/epoch on a single 1080Ti, so training around 10 epochs would be roughly 5 hours.

You can see the training time for each model in the training logs as well. 

For instance, under [EXPTS.md](https://github.com/TheShadow29/vognet-pytorch/blob/master/EXPTS.md#gt5-models-all-conc-strategies), say the `id= spat_vog_3Mar20`, the log is `https://drive.google.com/file/d/1_TRlAkqaYL0zg0zYnMmDMf_QkawOvZPr/view` and you can see total time taken in seconds. In this case it is 18969.9429 which translates to 5.2 hours.

For the P100 setting, it takes longer because batch size is smaller. I believe it took around 1 day to converge for the P100 setting.

Let me know if you have any trouble reproducing the numbers.

**Comment by TheShadow29** [comment]
I believe the issue is solved, feel free to re-open in case of any queries
